---
- name: Aplicar hardening en servidores Ubuntu
  hosts: ubuntu  # Se ejecuta solo en hosts del grupo ubuntu
  become: yes    # Ejecuta tareas como root

  tasks:
    # Tarea 1: Actualizar todos los paquetes
    - name: Actualizar sistema
      ansible.builtin.apt:
        state: latest
        update_cache: true  # Equivalente a apt update
        upgrade: dist #instala las actualizaciones de todos los paquetes equivale a sudo apt upgrade -y
      notify: Reiniciar sistema  # Llama al handler si hay actualizaciones

    # Tarea 2: Configurar UFW
    - name: Configurar firewall UFW
      community.general.ufw:
        rule: allow
        name: OpenSSH
        state: enabled  # Habilita UFW y solo permite SSH

    # Tarea 3: Configurar SSH seguro
    - name: Deshabilitar login root
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: PermitRootLogin no  # Deshabilita login como root
      notify: Reiniciar SSH  # Llama al handler si hay cambios

    - name: Forzar autenticación por clave
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: PasswordAuthentication no  # Solo permite claves SSH
      notify: Reiniciar SSH

    # Tarea 4: Instalar fail2ban
    - name: Instalar fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present  # Instala el paquete

    - name: Habilitar fail2ban
      ansible.builtin.service:
        name: fail2ban
        state: started
        enabled: yes  # Para que inicie al arranque

  handlers:
    # Handler 1: Reiniciar sistema después de actualizaciones
    - name: Reiniciar sistema
      ansible.builtin.reboot: #reiniciar sistema

    # Handler 2: Reiniciar servicio SSH
    - name: Reiniciar SSH
      ansible.builtin.systemd_service:
        name: ssh  # Nombre del servicio en Ubuntu
        state: restarted
